name: corp-rag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.*
  - numpy=1.26.*         # совместимо с faiss 1.8.x
  - pandas=2.2.*
  - networkx=3.3
  - pytorch=2.3.*        # conda-forge; MPS на macOS ARM
  - libmagic=5.*
  - tesseract=5.*
  - poppler=24.*
  - pypdf=4.*
  - openjdk=21
  - ffmpeg
  - pyarrow=16.*
  - uvicorn
  - pip:
      - "langchain>=0.2.11,<0.3"
      - "langchain-community>=0.2.11,<0.3"
      - "langchain-text-splitters>=0.2.2,<0.3"
      - "langchain-openai>=0.1.21,<0.2"
      - "langchainhub>=0.1.15,<0.2"
      - "unstructured>=0.14"
      - "langchain-unstructured>=0.1"
      - "pymupdf>=1.24"
      - "llama-cloud>=0.1.37"
      - "llama-parse>=0.1.6"
      - "sentence-transformers>=2.7,<3"
      - "huggingface_hub>=0.23"
      - "tqdm>=4.66"
      - "python-dotenv>=1.0"
      - "gigachat>=0.2.0"